### ISSUE TITLE
[Milestone] Foundation of js-waku docs

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#101]
**Planned start date**:
**Due date**:

# Summary

Provide basic js-waku documentation to enable JS developer to build on Waku.

# Acceptance Criteria

Guides are published for:

- usage of light push
- usage of filter
- usage of store
- bootstrapping

## Tasks

- [x] Quick start guide to use light push and filter
- [x] Guide for several bootstrap methods (ENR tree, static nodes, ENR tree + static) #100 
- [x] Guide to use store node

# RAID (Risks, Assumptions, Issues and Dependencies)

- js-waku library needs to be working and stable
- js-waku dev needs to fix any bug encountered or missing API

**Comment by fryorcraken** [comment]
@LordGhostX Feel free to close is already done and pushed on `master1

**Comment by fryorcraken** [comment]
@LordGhostX all done? Shall we close?
