### ISSUE TITLE
Advanced docs for js-waku

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#104]
**Planned start date**:
**Due date**:

# Summary

Complement the current basic js-waku docs.

# Acceptance Criteria

The following guides are published:

- [x] Use `@waku/react`
- [ ] Use symmetric encryption/decryption
- [ ] Use ECIES encryption/decryption
- [ ] Use noise for device pairing
- [x] Instructions to debug your web app when using js-waku
- [x] js-waku in NodeJS
- [x] Instructions to run a nwaku node for local js-waku browser development

## Tasks

- [ ] https://github.com/waku-org/docs.waku.org/issues/26

# RAID (Risks, Assumptions, Issues and Dependencies)

- js-waku's API needs to be stable and reliable
- js-waku devs need to provide support and fix any raised bug

**Comment by LordGhostX** [comment]
**Weekly Update**

_achieved_: what was achieved this week; must remain on one line.
_next_: create guide on `@waku/react` and debugging js-waku web apps

**Comment by fryorcraken** [comment]
Also explain js-waku in NodeJS.
Current recommendations for NodeJS
And that it doesn't make sense to use BE/FE model like NestJS or express.

**Comment by fryorcraken** [comment]
Also explain local development setup. Running nwaku docker with ws (not wss), serving website locally and the fact that secure context protection from the browser (no ws in https) doesn't apply when the website is served locally (127.0.0.1 url)

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: added guide for `js-waku` debugging and running in NodeJS
- _next_: `js-waku` encryption guides

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: added guide for local development with nwaku

**Comment by fryorcraken** [comment]
Manage filter subscription to be added here cc @danisharora099

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: added `createSubscription()` docs in #128
- _next_: tackle @waku/sdk deprecated namespace #131, create filter management docs

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: filter management docs
- _next_: deprecated namespace docs #131

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: published manage filter guide, finished react docs
- _next_: ECIES and symmetric encryption/decryption

**Comment by fryorcraken** [comment]
@LordGhostX I think we can close this issue and track encryption with #125
