### ISSUE TITLE
[Epic] Waku Technical Overview

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#105]
**Planned start date**:
**Due date**:

# Summary

Provide a technical overview of Waku that includes architecture aspect, roadmap and perfomance.

# Acceptance Criteria

- [x] Waku Network topology overview
- [x] Highlight of roadmap for 2023 (see waku.org landing)
- [x] Waku's state in term of decentralized and wanted properties (could use table done at August Town Hall)
- [x] Link to track Waku's epics and milestone?
- [x] Learning from latest DST simulations: reliability, performance, etc (Waku Research will write an article, we could do a summary of said article in the docs and point to it)
- [x] Client architecture https://miro.com/app/board/uXjVMD62hMA=/

## Tasks

- [x] https://github.com/waku-org/docs.waku.org/issues/20
- [x] https://github.com/waku-org/docs.waku.org/issues/62
- [x] https://github.com/waku-org/docs.waku.org/issues/98
- [x] https://github.com/waku-org/docs.waku.org/issues/38
- [x] https://github.com/waku-org/docs.waku.org/issues/7

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by fryorcraken** [comment]
Still needs to be done. Will probably need a brainstorm on this one.
