### ISSUE TITLE
[Epic] RLN Overview

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#106]
**Planned start date**: 31Oct 2023
**Due date**:

# Summary

Provide a technical overview of the work of RLN and how Waku uses it to enable spam protection.

# Acceptance Criteria

- [x] High level explanation of RLN and how it leverage zero-knowledge to rate limit while providing some privacy preserving properties
- [x] High level explanation on how Waku uses RLN for basic DoS protection
- [x] Call to action for a developer to be involved.

Note that using RLN in a SDK is not part of the scope of said issue.

## Tasks

- [ ] https://github.com/waku-org/docs.waku.org/issues/9

# RAID (Risks, Assumptions, Issues and Dependencies)

- Depends on Waku Research milestone 3.1 DoS Requirements and Design and 3.2 Basic DoS Protection in Production.
