### ISSUE TITLE
[Epic] Review Usage and Metrics 2023 Q3

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#107]
**Planned start date**:
**Due date**: 30 Sep 2023

# Summary

Review metrics such as page view and also polling of community to understand the most used docs and wanted SDKs/Docs.

# Acceptance Criteria

- [x] Stats for docs.waku.org are working
- [ ] Review stats for docs.waku.org
- [x] Poll to know preferred languages SDK and Docs is out

## Tasks

# RAID (Risks, Assumptions, Issues and Dependencies)

- Metrics issue: https://github.com/acid-info/logos-docusaurus-plugins/issues/105

**Comment by fryorcraken** [comment]
For the poll of preferred languages. Let's be sure to include:
- JavaScript (Browser)
- TypeScript (Browser)
- NodeJS
- Deno
- React Native
- Golang
- Python
- Rust
- Nim
- Dart/Flutter

And more

**Comment by LordGhostX** [comment]
SDK/Language Poll: https://discord.com/channels/1110799176264056863/1111568123007606855/1149298157306531890

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: published the language/SDK poll on Discord
- _next_: publish the poll on socials for more visibility and responses

**Comment by fryorcraken** [comment]
> * _next_: publish the poll on socials for more visibility and responses

Is this done?
