### ISSUE TITLE
ethcc milestone deliverables

### ISSUE THREAD

**Issue by hackyguru** [waku-org/docs.waku.org#79]
it would be great to have these assets on the checklist delivered for ethcc so that we can start shilling our docs page and share it with devs for feedback :

- [x] js-waku side of docs
- [x] analytics for docs : note down page views before and after ethcc
- [x] publish the new docs in docs.waku.org

**Comment by fryorcraken** [comment]
@hackyguru @LordGhostX looks like this can be closed.
